name: deploy_test
on:
  workflow_dispatch:
env:
  REEARTH_URL: test.reearth.dev
  GCS_DEST: gs://test.reearth.dev/
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy_test:
    name: Deploy test env
    runs-on: ubuntu-latest
    if: github.event.repository.full_name == 'reearth/reearth-web'
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/nightly
          file: reearth-web_nightly.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: tar -xvf reearth-web_nightly.tar.gz
      - name: rsync
        run: gsutil -m -h "Cache-Control:no-store" rsync -x "^reearth_config\\.json$" -dr reearth-web/ $GCS_DEST
  slack-notification:
    if: success() || failure()
    name: Slack Notification
    needs:
      - deploy_test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        if: always()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
