project_name: reearth
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/reearth
    flags:
      - -tags=release
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -buildid=
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
changelog:
  skip: true
release:
  disable: true
