version: '3'
services:
  reearth:
    image: reearth/reearth:latest
    environment:
      REEARTH_DB: mongodb://reearth-mongo
    ports:
      - 8080:8080
    # env_file:
    #  - ./.env
    links:
      - reearth-mongo
    depends_on:
      - reearth-mongo
    volumes:
      - ./data:/reearth/data
  reearth-mongo:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
