comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
ignore:
  - server/**/*_gen.go
  - server/**/*_test.go
  - server/**/doc.go
  - server/**/testdata
  - server/internal/adapter/gql/generated.go
  - server/tools
  - server/main.go
  - server/tools.go
  - web/**/*.test.ts
  - web/**/*.test.tsx
  - web/**/*.stories.ts
  - web/**/*.stories.tsx
  - web/.storybook
  - web/bin
  - web/src/gql/graphql-client-api.tsx
